name: Build and Deploy mkdocs and Previews
on:
  push:
    branches:
      - master 
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
permissions:
  contents: write
concurrency: preview-${{ github.ref }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docs
        uses: actions/checkout@v3
        with:
          path: docs
      - name: Checkout spack-ucdavis
        uses: actions/checkout@v3
        with:
          repository: ucdavis/spack-ucdavis
          path: spack-ucdavis
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-macros-plugin
      - name: mkdocs build
        working-directory: docs
        run: mkdocs build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site/
          clean-exclude: pr-preview/
          force: false
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docs
        uses: actions/checkout@v3
        with:
          path: docs
      - name: Checkout spack-ucdavis
        uses: actions/checkout@v3
        with:
          repository: ucdavis/spack-ucdavis
          path: spack-ucdavis
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-macros-plugin
      - name: mkdocs build
        working-directory: docs
        run: mkdocs build
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site/
